server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务器注册中心
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
      web-context-unify: false # controller层的方法对service层调用不认为是同一个根链路
      datasource: # sentinel用nacos作为数据源的配置
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow # com.alibaba.cloud.sentinel.datasource.RuleType
        flux-control: # 流控管理（这个名称可以自定义）
          nacos: # 告诉sentinel用nacos作为数据源
            data-id: feign-test_flux-control_config.json # 配置中心里执行文件的dataId
            server-addr: localhost:8848 # nacos的地址
            rule-type: flow # 指定文件配置的是那种规则
        degrade-control: # 熔断管理（这个名称可以自定义）
          nacos:
            data-id: feign-test_degrade-control_config.json
            server-addr: localhost:8848
            rule-type: degrade
        param-flow-control: # 热点参数管理（这个名称可以自定义）
          nacos:
            data-id: feign_test-hot_flux-config.json
            server-addr: localhost:8848
            rule-type: param-flow